---
  default:

    titlePanelLabel: "Optimalizácia konfiguračných parametrov predikčných metód"
    descriptionPanelLabel: >
      Aplikácia umožňuje používateľovi vybrať si predikčný a optimalizačný
      algoritmus, pomocou ktorých bude nájdená optimálna hodnota vybranej
      fitness funkcie. Používateľ má možnosť konfigurovať parametre
      optimalizačnej a interval jednotlivých parametrov predikčnej metódy.
      Nad dátami, ktoré vloží bude vypočítaná najmenšia odchýlka a parametre,
      ktoré k tomuto výsledku viedli. Dáta musia byť vo formáte CSV, kde
      prvý stĺpec timestamp označuje čas merania, a stĺpec value hodnotu tohto
      merania.

    predictionAlgorithmsLabel: "Predikčné algoritmy"
    optimizationAlgorithmsLabel: "Optimalizačné algoritmy"
    fitnessFunctionsLabel: "Fitness funkcia"
    inputFileLabel: "Vstupné dáta"
    inputFileButton: "Vložiť..."
    inputFilePlaceholder: "Nie je zvolený žiadny súbor"

    measurementsPerDay:
      label: "Počet meraní za deň"
      min: 1
      max: 1440
      default: 96

    trainingSetRange:
      label: "Rozsah trénovacích dát"
      separator: " do "
      format: "yyyy-mm-dd"

    testingSetRange:
      label: "Rozsah testovacích dát"
      separator: " do "
      format: "yyyy-mm-dd"

    optimizationParametersLabel: "Parametre optimalizačnej metódy"
    predictionParametersLabel: "Parametre predikčnej metódy"
    submitButtonLabel: "Vypočítaj"

    results:
      dygraph:
        realValuesLabel: "Reálne dáta"
        predictedValuesLabel: "Predpovedané hodnoty"
        annotationLabel: "Testovacia množina"
      solutionColumns:
        - "Názov parametru"
        - "Optimálna hodnota"
      fitnessColumns:
        - "Názov chyby"
        - "Veľkosť chyby"
      label: "Reálne a predikované hodnoty"
      xlabel: "Poradové číslo merania"
      ylabel: "Namerané a predikované dáta"
      valueLabel: "Najnižšia dosiahnutá chyba"
      solutionLabel: "Optimálna konfigurácia parametrov"

    validation:
      file: "Súbor nie je vo formáte CSV"
      csv: "Súbor CSV nemá požadované stĺpce"
      period: "Zvolený počet meraní za deň nezodpovedá vloženému súboru"
      dates: "Trénovacia množina sa nesmie prekrývať s testovacou, počiatočný dátum nesmie byť neskôr posledný dátum"
      params: "Minimálna hodnota parametrov predikčnej metódy musí byť menšia alebo rovná maximálnej hodnote"

    tooltips:
      predictionAlgorithms: "Kliknutím vyberte predičkný algoritmus, ktorého parametre budú optimalizované"
      optimizationAlgorithms: "Kliknutím vyberte optimalizačný algoritmus, ktorý bude optimalizovať parametre"
      inputFile: "Vyberte CSV súbor so stĺpcami timestamp a value"
      measurementsPerDay: "Vyberte frekvenciu meraní za deň"
      trainingSetRange: "Kliknutím zmeňte rozmedzie dát určených na trénovanie"
      testingSetRange: "Kliknutím zmeňte rozmedzie dát určených na testovanie"
      fitnessFunction: "Kliknutím vyberte funkciu na meranie chyby predpovede"
