---
  default:

    00-svr-predict:
      svmType: "eps-svr"
      kernelFunction: "rbfdot"
      scaled: FALSE

    02-pso-optimize:
      animation: FALSE
      vmax:
        - 0.05
        - 0.05
        - 0.05
