---
  default:

    03-arima-predict:
      maximumOrder: 4

    03-svr-predict:
      svmType: "eps-svr"
      kernelFunction: "rbfdot"
      scaled: FALSE

    04-psoptim-optimize:
      animation: FALSE
      vmax:
        - 0.05
        - 0.05
        - 0.05

    04-pso-optimize:
      d: 5
      vmax: 1
      type: "SPSO2007"
