---
  default:

    numberOfPredictionAlgorithms: 2
    numberOfOptimizationAlgorithms: 1
    numberOfFitnessFunctions: 5

    predictionAlgorithms:
      - label: "SVR"
        parameterLabels:
          - "C"
          - "epsilon"
        readDataFn: "svr.readDataFn"
        predictFn: "svr.predictFn"
        predictDataFn: "svr.predictDataFn"
        numberOfPredictionParameters: 4
        predictionParameters:
          - id: "minC"
            label: "Minimum C"
            value: 0.5
            min: 0.001
            max: 10
            step: 0.001
          - id: "maxC"
            label: "Maximum C"
            value: 1.5
            min: 0.001
            max: 10
            step: 0.001
          - id: "minEpsilon"
            label: "Minimum epsilon"
            value: 0.05
            min: 0.001
            max: 10
            step: 0.001
          - id: "maxEpsilon"
            label: "Maximum epsilon"
            value: 0.2
            min: 0.001
            max: 10
            step: 0.001

      - label: "ARIMA"
        parameterLabels:
          - "p"
          - "d"
          - "q"
        readDataFn: "arima.readDataFn"
        predictFn: "arima.predictFn"
        predictDataFn: "arima.predictDataFn"
        numberOfPredictionParameters: 6
        predictionParameters:
          - id: "minP"
            label: "Minimum p"
            value: 1
            min: 0
            max: 10
            step: 1
          - id: "maxP"
            label: "Maximum p"
            value: 2
            min: 0
            max: 10
            step: 1
          - id: "minD"
            label: "Minimum d"
            value: 1
            min: 0
            max: 10
            step: 1
          - id: "maxD"
            label: "Maximum d"
            value: 2
            min: 0
            max: 10
            step: 1
          - id: "minQ"
            label: "Minimum q"
            value: 1
            min: 0
            max: 10
            step: 1
          - id: "maxQ"
            label: "Maximum q"
            value: 2
            min: 0
            max: 10
            step: 1


    optimizationAlgorithms:
      - label: "Umelá kolónia včiel"
        optimizeFn: "pso.optimizeFn"
        numberOfOptimizationParameters: 2
        optimizationParameters:
          - id: "numberOfParticles"
            label: "Počet častíc"
            value: 20
            min: 1
            max: 1000
          - id: "maxIterations"
            label: "Maximum iterácií"
            value: 20
            min: 1
            max: 1000


    fitnessFunctions:
      - label: "MFE"
        errorFn: "mfe"
      - label: "MAE"
        errorFn: "mae"
      - label: "MPE"
        errorFn: "mpe"
      - label: "MAPE"
        errorFn: "mape"
      - label: "MSE"
        errorFn: "mse"
