---
  default:

    numberOfPredictionAlgorithms: 3
    numberOfOptimizationAlgorithms: 3
    numberOfFitnessFunctions: 3


    predictionAlgorithms:
      - label: "SVR"
        parameterLabels:
          - "C"
          - "epsilon"
        prepareFn: "svr.prepareFn"
        predictFn: "svr.predictFn"
        predictDataFn: "svr.predictDataFn"
        numberOfPredictionParameters: 4
        predictionParameters:
          - id: "minC"
            label: "Minimum C"
            value: 100
            min: 0.001
            max: 2500
            step: 0.001
          - id: "maxC"
            label: "Maximum C"
            value: 1000
            min: 0.001
            max: 2500
            step: 0.001
          - id: "minEpsilon"
            label: "Minimum epsilon"
            value: 50
            min: 0
            max: 1000
            step: 0.001
          - id: "maxEpsilon"
            label: "Maximum epsilon"
            value: 200
            min: 0
            max: 1000
            step: 0.001

      - label: "ARIMA"
        parameterLabels:
          - "p"
          - "d"
          - "q"
        prepareFn: "arima.prepareFn"
        predictFn: "arima.predictFn"
        predictDataFn: "arima.predictDataFn"
        numberOfPredictionParameters: 6
        predictionParameters:
          - id: "minP"
            label: "Minimum p"
            value: 0
            min: 0
            max: 5
            step: 1
          - id: "maxP"
            label: "Maximum p"
            value: 2
            min: 0
            max: 5
            step: 1
          - id: "minD"
            label: "Minimum d"
            value: 0
            min: 0
            max: 4
            step: 1
          - id: "maxD"
            label: "Maximum d"
            value: 2
            min: 0
            max: 4
            step: 1
          - id: "minQ"
            label: "Minimum q"
            value: 0
            min: 0
            max: 5
            step: 1
          - id: "maxQ"
            label: "Maximum q"
            value: 2
            min: 0
            max: 5
            step: 1

      - label: "Náhodné lesy"
        parameterLabels:
          - "Počet stromov"
          - "Veľkosť uzla"
        prepareFn: "rf.prepareFn"
        predictFn: "rf.predictFn"
        predictDataFn: "rf.predictDataFn"
        numberOfPredictionParameters: 4
        predictionParameters:
          - id: "minNtree"
            label: "Minimum stromov"
            value: 40
            min: 1
            max: 1000
            step: 1
          - id: "maxNtree"
            label: "Maximum stromov"
            value: 80
            min: 1
            max: 1000
            step: 1
          - id: "minNodesize"
            label: "Minimálna veľkosť uzlov"
            value: 5
            min: 0
            max: 100
            step: 1
          - id: "maxNodesize"
            label: "Maximum veľkosť uzlov"
            value: 20
            min: 0
            max: 100
            step: 1


    optimizationAlgorithms:
      - label: "PSO z knižnice pso"
        optimizeFn: "pso.optimizeFn"
        numberOfOptimizationParameters: 2
        optimizationParameters:
          - id: "numberOfParticles"
            label: "Počet častíc"
            value: 20
            min: 1
            max: 1000
          - id: "maxIterations"
            label: "Maximum iterácií"
            value: 20
            min: 1
            max: 1000

      - label: "PSO z knižnice psoptim"
        optimizeFn: "psoptim.optimizeFn"
        numberOfOptimizationParameters: 2
        optimizationParameters:
          - id: "numberOfParticles"
            label: "Počet častíc"
            value: 20
            min: 1
            max: 1000
          - id: "maxIterations"
            label: "Maximum iterácií"
            value: 20
            min: 1
            max: 1000

      - label: "ABC"
        optimizeFn: "abc.optimizeFn"
        numberOfOptimizationParameters: 3
        optimizationParameters:
          - id: "maxIterations"
            label: "Maximum iterácií"
            value: 20
            min: 1
            max: 1000
          - id: "foodNumber"
            label: "Maximum zdrojov jedla"
            value: 20
            min: 1
            max: 500
          - id: "limit"
            label: "Maximum iterácií na zabudnutie zdroja"
            value: 5
            min: 1
            max: 100


    fitnessFunctions:
      # - label: "MFE"
      #   errorFn: "mfe"
      - label: "MAE"
        errorFn: "mae"
      # - label: "MPE"
      #   errorFn: "mpe"
      - label: "MAPE"
        errorFn: "mape"
      - label: "MSE"
        errorFn: "mse"
