---
  default:

    predictionAlgorithms:
      - label: "SVR"
        description: >
          Regresia založená na podporných vektoroch, <br/>
          optimalizovanými parametrami sú C a epsilon: <br/>
          C - cena za prekročenie hranice <br/>
          epsilon - hranica <br/>
        parameterLabels:
          - "C"
          - "epsilon"
        prepareFn: "svr.prepareFn"
        predictFn: "svr.predictFn"
        predictDataFn: "svr.predictDataFn"
        predictionParameters:
          - id: "minC"
            label: "Minimum C"
            value: 100
            min: 0.001
            max: 2500
            step: 0.001
          - id: "maxC"
            label: "Maximum C"
            value: 1000
            min: 0.001
            max: 2500
            step: 0.001
          - id: "minEpsilon"
            label: "Minimum epsilon"
            value: 50
            min: 0
            max: 1000
            step: 0.001
          - id: "maxEpsilon"
            label: "Maximum epsilon"
            value: 200
            min: 0
            max: 1000
            step: 0.001

      - label: "ARIMA"
        description: >
          Autoregresívny integrovaný model kĺzavého priemeru, <br/>
          optimalizovanými parametrami sú p, d, q: <br/>
          p - rad autoregresívneho modelu <br/>
          d - stupeň derivovania <br/>
          q - rad modelu kĺzavého primeru <br/>
        parameterLabels:
          - "p"
          - "d"
          - "q"
        prepareFn: "arima.prepareFn"
        predictFn: "arima.predictFn"
        predictDataFn: "arima.predictDataFn"
        predictionParameters:
          - id: "minP"
            label: "Minimum p"
            value: 0
            min: 0
            max: 9
            step: 1
          - id: "maxP"
            label: "Maximum p"
            value: 2
            min: 0
            max: 9
            step: 1
          - id: "minD"
            label: "Minimum d"
            value: 0
            min: 0
            max: 9
            step: 1
          - id: "maxD"
            label: "Maximum d"
            value: 2
            min: 0
            max: 9
            step: 1
          - id: "minQ"
            label: "Minimum q"
            value: 0
            min: 0
            max: 9
            step: 1
          - id: "maxQ"
            label: "Maximum q"
            value: 2
            min: 0
            max: 9
            step: 1

      - label: "Náhodné lesy"
        description: >
          Náhodné lesy, <br/>
          optimalizovanými parametrami sú počet stromov a veľkosť uzla: <br/>
          počet stromov - počet by nemal byť veľmi malé číslo <br/>
          veľkosť uzla - väčšie hodnoty spôsobujú rast nízkych stromov <br/>
        parameterLabels:
          - "Počet stromov"
          - "Veľkosť uzla"
        prepareFn: "rf.prepareFn"
        predictFn: "rf.predictFn"
        predictDataFn: "rf.predictDataFn"
        predictionParameters:
          - id: "minNtree"
            label: "Minimum stromov"
            value: 40
            min: 1
            max: 1000
            step: 1
          - id: "maxNtree"
            label: "Maximum stromov"
            value: 80
            min: 1
            max: 1000
            step: 1
          - id: "minNodesize"
            label: "Minimálna veľkosť uzlov"
            value: 5
            min: 0
            max: 100
            step: 1
          - id: "maxNodesize"
            label: "Maximum veľkosť uzlov"
            value: 20
            min: 0
            max: 100
            step: 1


    optimizationAlgorithms:
      - label: "PSO z knižnice pso"
        description: >
          Optimalizácia rojom častíc, <br/>
          nastaviteľnými parametrami sú počet častíc a maximálny počet iterácií <br/>
          počet častíc - priamo úmerný počtu preskúmaných riešení <br/>
          maximálny počet iterácií - ukončovacia podmienka v prípade, že sa skôr nenájde optimálne riešenie <br/>
        optimizeFn: "pso.optimizeFn"
        optimizationParameters:
          - id: "numberOfParticles"
            label: "Počet častíc"
            value: 20
            min: 1
            max: 1000
          - id: "maxIterations"
            label: "Maximum iterácií"
            value: 20
            min: 1
            max: 1000

      - label: "PSO z knižnice psoptim"
        description: >
          Optimalizácia rojom častíc, <br/>
          nastaviteľnými parametrami sú počet častíc a maximálny počet iterácií <br/>
          počet častíc - priamo úmerný počtu preskúmaných riešení <br/>
          maximálny počet iterácií - ukončovacia podmienka v prípade, že sa skôr nenájde optimálne riešenie <br/>
        optimizeFn: "psoptim.optimizeFn"
        optimizationParameters:
          - id: "numberOfParticles"
            label: "Počet častíc"
            value: 20
            min: 1
            max: 1000
          - id: "maxIterations"
            label: "Maximum iterácií"
            value: 20
            min: 1
            max: 1000

      - label: "ABC"
        description: >
          Umelá kolónia včiel, <br/>
          nastaviteľnými parametrami sú počet zdrojov jedla, maximálny počet iterácií a maximálny počet iterácií zabudnutie zdroja potravy <br/>
          počet zdrojov jedla - zodpovedá počtu robotníc a prehľadávačok <br/>
          maximálny počet iterácií - ukončovacia podmienka v prípade, že sa skôr nenájde optimálne riešenie <br/>
          maximálny počet iterácií na zabudnutie zdroja - zdroj je zabudnutý v prípade, že sa nezvýšilo množstvo nektáru za daný počet cyklov <br/>
        optimizeFn: "abc.optimizeFn"
        optimizationParameters:
          - id: "maxIterations"
            label: "Maximum iterácií"
            value: 20
            min: 1
            max: 1000
          - id: "foodNumber"
            label: "Počet zdrojov jedla"
            value: 20
            min: 1
            max: 500
          - id: "limit"
            label: "Maximum iterácií na zabudnutie zdroja"
            value: 5
            min: 1
            max: 100


    fitnessFunctions:
      # - label: "MFE"
      #   description: ""
      #   errorFn: "mfe"
      - label: "MAE"
        description: >
          <br/> Stredná absolútna chyba <br/>
        errorFn: "mae"
      # - label: "MPE"
      #   description: ""
      #   errorFn: "mpe"
      - label: "MAPE"
        description: >
          <br/> Stredná aboslútna percentuálna chyba <br/>
        errorFn: "mape"
      - label: "MSE"
        description: >
          <br/> Stredná štvorcová chyba <br/>
        errorFn: "mse"
