---
  default:

    ui:
      titlePanelLabel: "Optimalizácia konfiguračných parametrov predikčných metód"
      descriptionPanelLabel: >
        Aplikácia umožňuje používateľovi vybrať si predikčný a optimalizačný
        algoritmus, pomocou ktorých bude nájdená optimálna hodnota vybranej
        fitness funkcie. Používateľ má možnosť konfigurovať parametre
        optimalizačnej a interval jednotlivých paramtrov predikčnej metódy.
        Nad dátami, ktoré vloží bude vypočítaná najmenšia odchýlka a parametre,
        ktoré k tomuto výsledku viedli. Dáta musia byť vo formáte CSV, kde
        prvý stĺpec timestamp označuje čas merania, a stĺpec value hodnotu tohto
        merania.

      predictionAlgorithmsLabel: "Predikčné algoritmy"
      optimizationAlgorithmsLabel: "Optimalizačné algoritmy"
      fitnessFunctionsLabel: "Fitness funkcia"
      inputFileLabel: "Vstupné dáta"

      measurementsPerDay:
        label: "Počet meraní za deň"
        min: 1
        max: 1440
        default: 96

      trainingDatasetProportion:
        label: "Pomer trénovacích dát"
        min: 0
        max: 1
        default: 0.9

      optimizationParametersLabel: "Parametre optimalizačnej metódy"
      predictionParametersLabel: "Parametre predikčnej metódy"
      submitButtonLabel: "Vypočítaj"

      results:
        label: "Vypočítané hodnoty"
        xlabel: "Poradové číslo merania"
        ylabel: "Namerané a predikované dáta"
        valueLabel: "Najnižšia dosiahnutá chyba"
        solutionLabel: "Optimálna konfigurácia parametrov"

      numberOfPredictionAlgorithms: 2
      numberOfOptimizationAlgorithms: 1
      numberOfFitnessFunctions: 5


    server:
      predictionAlgorithms:
        - label: "Regresné stromy"
          parameterLabels:
            - "C"
            - "epsilon"
          readDataFn: "svr.readDataFn"
          predictFn: "svr.predictFn"
          predictDataFn: "svr.predictDataFn"
          numberOfPredictionParameters: 4
          predictionParameters:
            - id: "minC"
              label: "Minimum C"
              value: 0.5
              min: 0.001
              max: 10
              step: 0.001
            - id: "maxC"
              label: "Maximum C"
              value: 1.5
              min: 0.001
              max: 10
              step: 0.001
            - id: "minEpsilon"
              label: "Minimum epsilon"
              value: 0.05
              min: 0.001
              max: 10
              step: 0.001
            - id: "maxEpsilon"
              label: "Maximum epsilon"
              value: 0.2
              min: 0.001
              max: 10
              step: 0.001

        - label: "Autoregresívny integrovaný model kĺzavého priemeru"
          parameterLabels:
            - "p"
            - "d"
            - "q"
          readDataFn: "arima.readDataFn"
          predictFn: "arima.predictFn"
          predictDataFn: "arima.predictDataFn"
          numberOfPredictionParameters: 6
          predictionParameters:
            - id: "minP"
              label: "Minimum p"
              value: 1
              min: 0
              max: 10
              step: 1
            - id: "maxP"
              label: "Maximum p"
              value: 2
              min: 0
              max: 10
              step: 1
            - id: "minD"
              label: "Minimum d"
              value: 1
              min: 0
              max: 10
              step: 1
            - id: "maxD"
              label: "Maximum d"
              value: 2
              min: 0
              max: 10
              step: 1
            - id: "minQ"
              label: "Minimum q"
              value: 1
              min: 0
              max: 10
              step: 1
            - id: "maxQ"
              label: "Maximum q"
              value: 2
              min: 0
              max: 10
              step: 1


      optimizationAlgorithms:
        - label: "Umelá kolónia včiel"
          optimizeFn: "pso.optimizeFn"
          numberOfOptimizationParameters: 2
          optimizationParameters:
            - id: "numberOfParticles"
              label: "Počet častíc"
              value: 20
              min: 1
              max: 1000
            - id: "maxIterations"
              label: "Maximum iterácií"
              value: 20
              min: 1
              max: 1000


      fitnessFunctions:
        - label: "MFE"
          errorFn: "mfe"
        - label: "MAE"
          errorFn: "mae"
        - label: "MPE"
          errorFn: "mpe"
        - label: "MAPE"
          errorFn: "mape"
        - label: "MSE"
          errorFn: "mse"
